### PR TITLE
lab-3 Drozhzha 751001

### PR DESCRIPTION
**Pull request by che6urek**
almost done (115 passing)

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
Improve isPrime

**Comment by aliaksandrkrasnou** [comment]
Call isString from string module (04 array tasks , getArratOfStrings method)

**Comment by aliaksandrkrasnou** [comment]
Map instead of for in conditions task (getcommondirextody

**Comment by aliaksandrkrasnou** [comment]
Types JS (theory)

**Comment by aliaksandrkrasnou** [comment]
Approved, okay 👍

**Comment by che6urek** [comment]
> Improve isPrime

done (Fermat primality test)

**Comment by che6urek** [comment]
> Call isString from string module (04 array tasks , getArratOfStrings method)

done

**Comment by che6urek** [comment]
> Types JS (theory)

learned

**Pull request closed without merging**
