### PR TITLE
Lab5 Krukovich Polina

### PR DESCRIPTION
**Pull request by palina-krukovich**
My lab 5 solution is [here](https://github.com/polina-krukovich/vue-news-app)

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
From my perspective, no matter if you're using scoped styles or not, it would be better to write class names using BEM or something similar. It could improve your component structure and give more understanding while coding, debugging, etc. 
For example _.header__container, not .container_ [here](https://github.com/polina-krukovich/vue-news-app/blob/master/src/components/Header.vue#L2). 
_.header__logo_, not _.logo_ [here](https://github.com/polina-krukovich/vue-news-app/blob/master/src/components/Header.vue#L3)
But it's up to you for now

**Comment by aliaksandrkrasnou** [comment]
No need to import _store_ [inside components](https://github.com/polina-krukovich/vue-news-app/blob/master/src/components/Navbar.vue#L21), because you registered store inside [main.js](https://github.com/polina-krukovich/vue-news-app/blob/master/src/main.js#L10) and it's available in all components as _this.$store_

**Comment by aliaksandrkrasnou** [comment]
v-bind:key is required while using v-for, especially with [custom components](https://github.com/polina-krukovich/vue-news-app/blob/master/src/components/NewsList.vue#L3)

**Comment by aliaksandrkrasnou** [comment]
Better to create a computed prop to handle [this logic](https://github.com/polina-krukovich/vue-news-app/blob/master/src/components/NewsListItem.vue#L8), it's quite a big one

**Comment by aliaksandrkrasnou** [comment]
Better to use _p_ or _span_ tag instead of _div_ for [displaying text](https://github.com/polina-krukovich/vue-news-app/blob/master/src/components/NewsListItem.vue#L14)

**Comment by aliaksandrkrasnou** [comment]
Try to avoid [magic numbers](https://github.com/polina-krukovich/vue-news-app/blob/master/src/App.vue#L30)

**Comment by palina-krukovich** [comment]
Added fixes and made responsive page design

**Comment by aliaksandrkrasnou** [comment]
Approved, well done 👍

**Pull request closed without merging**
