### PR TITLE
lab5

### PR DESCRIPTION
**Pull request by TJT812**

### CODE REVIEW

**Comment by TJT812** [comment]
751002

**Comment by aliaksandrkrasnou** [comment]
There is a good idea to use [Controller Input Component](https://reactjs.org/docs/forms.html#controlled-components) rather than just [fire callback function from props here](https://github.com/TJT812/React-new-app/blob/master/src/Components/Header/InputField.js#L14). This mechanism is called data binding and the reason of using this you could find if you follow the link above

**Comment by aliaksandrkrasnou** [comment]
Couldn't approve because I have seen a lot of parts of your code before (your Main.js is similar to [this Main.js](https://github.com/KyntsevichVova/NewsAPI-React) ,etc)

If you want an approval (1 or 0.5), I'm kindly asking you to avoid cheating, especially at this task. Please refactor your code 

I'll be able to check your solution by Wednesday if you want to

**Comment by TJT812** [comment]
Repository updated

**Comment by aliaksandrkrasnou** [comment]
[Yours](https://github.com/TJT812/React-new-app/commit/22ac5d8503a57ea19624a35c846efc492d1a1536#diff-ba63e93e97e1f1ec092381ebf58927bfR1) VS [PavelYakovlevich 2 days ago](https://github.com/Shutya/bsuir-751005/pull/50/files#diff-10448c9b6b4a62dbd0aa50ab4db5a065R1)
[Yours](https://github.com/TJT812/React-new-app/commit/22ac5d8503a57ea19624a35c846efc492d1a1536#diff-57aa11691094c3295e1f9dcbe8432ba2R1) VS [PavelYakovlevich 2 days ago](https://github.com/TJT812/React-new-app/commit/22ac5d8503a57ea19624a35c846efc492d1a1536#diff-57aa11691094c3295e1f9dcbe8432ba2R1)
[Yours](https://github.com/TJT812/React-new-app/commit/22ac5d8503a57ea19624a35c846efc492d1a1536#diff-7b7eaf66e72be05886552f6ecdb2384aR1) VS [PavelYakovlevich 2 days ago](https://github.com/Shutya/bsuir-751005/pull/50/files#diff-0f8659ac3c875fab6c98116187c1e4a9R1)
...

Don't waste your and my time pls, 4 tasks are quite enough for you 😊 👍

**Comment by TJT812** [comment]
:)

**Pull request closed without merging**
