### PR TITLE
Lab 5

### PR DESCRIPTION
**Pull request by ghost**
Solution for the fifth lab. Morozov 751001

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
1) Highly recommend to follow [Atomic Design Methodology](http://atomicdesign.bradfrost.com/chapter-2/) in order to create React Components, these principles might help you. 
For example, 

- create BaseButton Component with prop text (String). Also you could create some basic css stylesheet. Then try to enhance this component if you need to, for example class SearchButton extends BaseButton and this component will store specific logic for the Search component (some additional props, functions, etc). 
- Finally, you will get some number of base and extended components (_Atoms_). 5, 10, 15, it doesn't matter. Then try to combine these atoms in _Molecules_ (SearchButton and SearchInput inside one SearchBar component, etc)
- After that, create a set of _Organisms_ (SearchBar and SourcesBar could be joined into Header, etc)
- And now, we're ready to create a _Template_. Combine Header, Main and Footer components into one App component.

Also, it's recommended for an each component to be presented by its own .js file and being imported to the others 

2) Also try not to store logic inside _Atoms_ and _Molecules_ (fetch request for example). It's better to do this stuff inside _Organisms_ / _Templates_ because it will help you to create abstract basic/extended components, which could be reused or worked with some other http libs (instead of fetch). 
I guess you will need only componentDidMount hook 
`
  // inside Header/Sources Component
  componentDidMount() {
    fetch('https://sources-list.com/')
      .then(res => res.json())
      .then(json => this.setState({ sourcesList: json }));
  }
 //then use sourcesList as a Prop for class SoircesList (extrends BaseList) and render SourcesListItems
 //also handle click events from SoircesList inside this component and do some requests if you need to.
`

3) If you succeed with the following approach, you might be faced with the problem of sharing data among separate _Molecules_ / _Organisms_ / _Templates_.  [Redux](https://redux.js.org/introduction/getting-started) will help you ([examples](https://redux.js.org/introduction/getting-started#examples)). 

If you need more details, please contact me here or in telegram @aliaksandr_krasnou

**Comment by aliaksandrkrasnou** [comment]
And because we are using React now, don't control the DOM or perform DOM operations using document.getElementById or content.cloneNode(true).querySelector('.news__item'). You have to use React Components

**Comment by ghost** [comment]
Fine, I've rewritten everything. I hope it's ok.

**Comment by aliaksandrkrasnou** [comment]
0.5

**Comment by ghost** [comment]
I followed all recommendations and your advices. [Here](https://github.com/TemporarerAccount/rpi_lab5) is new one.

**Comment by aliaksandrkrasnou** [comment]
I couldn't approve because it seems like you're cheating a bit. 
You didn't have serviceWorkers previously and I guess there is no any reason of adding it [after our review](https://github.com/TemporarerAccount/rpi_lab5/commit/046e6980af36674b99fada24c8637d12d8f6e13c#diff-b2e07e313b9e12d48090686d144ebea9R1). 
Secondly, this is not your style of using [BEM approach](https://github.com/TemporarerAccount/rpi_lab5/commit/046e6980af36674b99fada24c8637d12d8f6e13c#diff-897d6d852dcf1144e184ee7ce03ae8b6R8).
Then [Model.js](https://github.com/TemporarerAccount/rpi_lab5/commit/046e6980af36674b99fada24c8637d12d8f6e13c#diff-96402e3967f40f890b345d1291b004b3R1) is not yours as I can see.
And more and more

If you want an approval (1 or 0.5), I'm kindly asking you to avoid cheating, especially at this task. 

I'll be able to check your solution by Wednesday if you want to

**Comment by ghost** [comment]
You are Absolutely mistaken about cheating. Honestly it's a bit offensively,but I understand your suspicion.
And I'm going to disprove that.

First thing first, yes, I added service worker without any reason(because I saw it in some projects).  I just thought it influences on something. To get rid of any troubles from start I added it. Moreover almost in every React tutorial they delete it. I just forgot to remove, that's all.
But in general - you are right. I didn't have it before. 

And get back to coping - yes, I just copied index.js, app.js. Because I did have a bit different files, and to rewrite project I needed to get default files. I could just start a new project or to copy them(rewrite them on my own).

I'm not sure what do you mean with that: "Secondly, this is not your style of using BEM approach.".  You showed me an example of a good project and I just based on it. As I mentioned I rewrote ALL project because there was no way to update it. Moreover I used style you want to see, not I do. That's why "it's not my style".

Model.js it's just a name. All code inside is mine. To prove it I added the [old](https://github.com/TemporarerAccount/rpi_lab5_old) project. To be more exactly I added old files, because all project was rewritten. I always copy files(if they work) before to start new project.

If I can somehow prove my innocence, please let me know, because all this project I did on my own. Moreover it costed me my mouse :) It's pity to realize dass it died with no sense.

**Comment by aliaksandrkrasnou** [comment]
Well, in that case, I'm sorry if I offended you. It'd be enough if you clean up your code. Because now it looks like a big copy-paste, that's why there were some suspicions. It's hard to define where was yours code and where was not. 
Cleaning up includes: 
* Remove all unnecessary files (find out if you need service workers or not)
* Reach an agreement on which approach you're using either BEM or other (of course I mean code refactoring using the selected approach)
* Refactor Model.js file and Main.js files because you don't need Model/View/Controller anymore (you're using React)

**Comment by ghost** [comment]
It's ok. I might be more attentive before push it on git. 
But now, I guess it should be fine.
I got dass "Service worker" does. It seems like I don't really need it :)

Also I realized what did you mean about MVC.  The problem is I've read [it](http://atomicdesign.bradfrost.com/chapter-2/), but there's nothing mentioned about logic. Where it should be. I saw in Kuncevich work that er used MVC(I think this fact confused you). I decided I should too. I tried to refactor my React components according to Atomic design, but still have no any mind where should I put the logic part.

Hope I missed nothing. Please, let me know if I should fix something up.

**Comment by ghost** [comment]
I also tried to follow [BEM](https://de.wikipedia.org/wiki/Block,_Element,_Modifier#Namenskonvention) approach. Unfortunately there's no article in English.

**Comment by aliaksandrkrasnou** [comment]
Model.js in his work is not a M letter from MVC. It's an API class, which handles http requests and is being called inside componentDidMount hook. Why I think this was ok in his case is that he took his old code from lab4 and reuse it in lab5. The only thing he missed is to rename this class. But Vladimir does know what he's doing. So I guess you didn't understand his solution correctly.

Atomic Principle is an abstract thing which might help you to understand a clear approach of how to think and develop in a component-oriented style. It will help you to create and combine React Components. All other tech stuff could be found on reactjs.org, stackoverflow, medium, etc. For instance [this tutorial could be easily found](https://www.robinwieruch.de/react-fetching-data/)

BEM: I gave a link to [BEM in English from Yandex](https://en.bem.info/methodology/) to all my groups at the first lessons

**Comment by aliaksandrkrasnou** [comment]
So I'm kindly asking to create a new solution. Not just copy-paste others solutions or parts of others solutions. This is the only thing which will definitely help you to gain some knowledge. Otherwise it's just a waste of your valued time. 4 tasks are enough, you could stop)

**Comment by ghost** [comment]
It doesn't go like that. I've wasted toooooo much time to give up. I really can't understand why you don't believe that's my project. It's not copy past absolutely(I would be glad to see from where I copied it). ALL copied parts I removed.  
You offer me to rewrite it, but I fear it will look the same. Because I've a base(I showed you today). And logic has been taken from the 4th lab. 
What should I do? Give up is not an option.

**Comment by aliaksandrkrasnou** [comment]
In PM reached an agreement on modification task using Redux. Success

**Comment by aliaksandrkrasnou** [comment]
Approved, well done 👍

**Pull request closed without merging**
