### PR TITLE
Lab5, 751001

### PR DESCRIPTION
**Pull request by KyntsevichVova**

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
Try to use [ES6 string concatenation `${}`](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings) as much as possible, [here](https://github.com/KyntsevichVova/NewsAPI-React/blob/master/src/App.js#L109) and [here for example](https://github.com/KyntsevichVova/NewsAPI-React/blob/master/src/App.js#L114)

**Comment by aliaksandrkrasnou** [comment]
In reason to increase code readability and enhance component reusability split [App.js](https://github.com/KyntsevichVova/NewsAPI-React/blob/master/src/App.js) file into separate files MoreButton .js, News.js, etc and import necessary components on demand

**Comment by aliaksandrkrasnou** [comment]
Would be useful for you to write some unit tests for you components

**Comment by KyntsevichVova** [comment]
I think I've fixed string interpolation and decomposition issues, not sure what to do about unit testing.

**Comment by aliaksandrkrasnou** [comment]
Gain basic knowledge on how to testing your components using [Jest for example](https://jestjs.io/docs/en/tutorial-react). Create some small tests, train your skills, try to mock events, handle clicks, analyze render output using snapshots, etc

**Comment by aliaksandrkrasnou** [comment]
Use const instead of let [here](https://github.com/KyntsevichVova/NewsAPI-React/blob/master/src/components/Article.js#L8)

**Comment by aliaksandrkrasnou** [comment]
Why coudn't [MoreButton](https://github.com/KyntsevichVova/NewsAPI-React/blob/master/src/components/MoreButton.js#L8) use an [InputButton](https://github.com/KyntsevichVova/NewsAPI-React/blob/master/src/components/InputButton.js) inside? As well as a [SourceButton](https://github.com/KyntsevichVova/NewsAPI-React/blob/master/src/components/SourceButton.js#L6)?
I mean 
`
.div className="moreButtonWrapper"
  < InputButton ... >Show more< / InputButton >   
/div
`

**Comment by KyntsevichVova** [comment]
I fixed let => const and used InputButton in MoreButton, I'll try to think about SourceButton as well.
I don't think it will work well, because SourceButton has more attributes - id and toggled state

**Comment by KyntsevichVova** [comment]
Now SourceButton uses InputButton

**Comment by aliaksandrkrasnou** [comment]
I guess _id_ could be passed as a prop to the InputButton and you could use id as an optional prop inside InputButton.
As far as I can see _toggled_ does influence only on className. So you could pass this className as a prop from SourceButton to the InputButton.

**Comment by KyntsevichVova** [comment]
Yes, I did something similar

**Comment by aliaksandrkrasnou** [comment]
Approved, nice 👍

**Pull request closed without merging**
