### PR TITLE
lab-4

### PR DESCRIPTION
**Pull request by AlexPetul**
My lab 4 solution is [here](https://github.com/AlexPetul/lab-4-NewsApi)

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
More semantic

**Comment by aliaksandrkrasnou** [comment]
Waiting for fixes

**Comment by AlexPetul** [comment]
Updated. Please, read README, all information is there.

**Comment by aliaksandrkrasnou** [comment]
Approved, okay 👍

**Pull request closed without merging**
