### PR TITLE
Lab#5 by Bitkin Nikita 751001

### PR DESCRIPTION
**Pull request by nik123bitkin**
My lab 5 solution is [here](https://github.com/nik123bitkin/news-api-react)

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
1) Highly recommend to follow [Atomic Design Methodology](http://atomicdesign.bradfrost.com/chapter-2/) in order to create React Components, these principles might help you. 
For example, 

- create BaseButton Component with prop text (String). Also you could create some basic css stylesheet. Then try to enhance this component if you need to, for example class SearchButton extends BaseButton and this component will store specific logic for the Search component (some additional props, functions, etc). 
- Finally, you will get some number of base and extended components (_Atoms_). 5, 10, 15, it doesn't matter. Then try to combine these atoms in _Molecules_ (SearchButton and SearchInput inside one SearchBar component, etc)
- After that, create a set of _Organisms_ (SearchBar and SourcesBar could be joined into Header, etc)
- And now, we're ready to create a _Template_. Combine Header, Main and Footer components into one App component.

2) Also try not to store logic inside _Atoms_ and _Molecules_ (fetch request for example). It's better to do this stuff inside _Organisms_ / _Templates_ because it will help you to create abstract basic/extended components, which could be reused or worked with some other http libs (instead of fetch). 
I guess you will need only componentDidMount hook 
`
  // inside Header/Sources Component
  componentDidMount() {
    fetch('https://sources-list.com/')
      .then(res => res.json())
      .then(json => this.setState({ sourcesList: json }));
  }
 //then use sourcesList as a Prop for class SoircesList (extrends BaseList) and render SourcesListItems
 //also handle click events from SoircesList inside this component and do some requests if you need to.
`

3) If you succeed with the following approach, you might be faced with the problem of sharing data among separate _Molecules_ / _Organisms_ / _Templates_.  [Redux](https://redux.js.org/introduction/getting-started) will help you ([examples](https://redux.js.org/introduction/getting-started#examples)). 

If you need more details, please contact me here or in telegram @aliaksandr_krasnou

**Comment by aliaksandrkrasnou** [comment]
Approved 0.5

**Comment by nik123bitkin** [comment]
I changed the component structure of the application. Some code snippets still need to be checked, but i would be grateful for your opinion about this try

**Comment by aliaksandrkrasnou** [comment]
Is _class_ instead of _className_ allowed now in [JSX templates](https://github.com/nik123bitkin/news-api-react/commit/3e6bc2ebf1b7588a8553ad698511c4231d618965#diff-1a890e504f2cd510ab8322d6b4e40e3cR7)?

**Comment by aliaksandrkrasnou** [comment]
It seems to me that [.app__btn](url) could be defined inside Button.js rather than passing to Button component from [FilterButton](https://github.com/nik123bitkin/news-api-react/commit/3e6bc2ebf1b7588a8553ad698511c4231d618965#diff-1a890e504f2cd510ab8322d6b4e40e3cR7), [MoreButton](https://github.com/nik123bitkin/news-api-react/commit/3e6bc2ebf1b7588a8553ad698511c4231d618965#diff-c8152f7e23040a68089e397f85c1eb68R8) and [SourceButton](https://github.com/nik123bitkin/news-api-react/commit/3e6bc2ebf1b7588a8553ad698511c4231d618965#diff-42a2c41fa4604a0e701665159a7c6419R7). This class is a common one for all these buttons so it could be considered as a basic class defined inside Button. And you use _.btn__sources_ class and others in order to enhance functionality of Button component (styles I mean, but its the same in that case)

**Comment by nik123bitkin** [comment]
Speaking about class and className, this is just a property name. In the bottom level component Button I have "className = {this.props.class}"

**Comment by aliaksandrkrasnou** [comment]
Approved, well done 👍

**Pull request closed without merging**
