### PR TITLE
LAB-5

### PR DESCRIPTION
**Pull request by DannnYXZ**

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
1) Highly recommend to follow [Atomic Design Methodology](http://atomicdesign.bradfrost.com/chapter-2/) in order to create React Components, these principles might help you. 
For example, 

- create BaseButton Component with prop text (String). Also you could create some basic css stylesheet. Then try to enhance this component if you need to, for example class SearchButton extends BaseButton and this component will store specific logic for the Search component (some additional props, functions, etc). 
- Finally, you will get some number of base and extended components (_Atoms_). 5, 10, 15, it doesn't matter. Then try to combine these atoms in _Molecules_ (SearchButton and SearchInput inside one SearchBar component, etc)
- After that, create a set of _Organisms_ (SearchBar and SourcesBar could be joined into Header, etc)
- And now, we're ready to create a _Template_. Combine Header, Main and Footer components into one App component.

2) Also try not to store logic inside _Atoms_ and _Molecules_ (fetch request for example). It's better to do this stuff inside _Organisms_ / _Templates_ because it will help you to create abstract basic/extended components, which could be reused or worked with some other http libs (instead of fetch). 
I guess you will need only componentDidMount hook 
`
  // inside Header/Sources Component
  componentDidMount() {
    fetch('https://sources-list.com/')
      .then(res => res.json())
      .then(json => this.setState({ sourcesList: json }));
  }
 //then use sourcesList as a Prop for class SoircesList (extrends BaseList) and render SourcesListItems
 //also handle click events from SoircesList inside this component and do some requests if you need to.
`

3) If you succeed with the following approach, you might be faced with the problem of sharing data among separate _Molecules_ / _Organisms_ / _Templates_.  [Redux](https://redux.js.org/introduction/getting-started) will help you ([examples](https://redux.js.org/introduction/getting-started#examples)). 

If you need more details, please contact me here or in telegram @aliaksandr_krasnou

**Comment by DannnYXZ** [comment]
OK. Thank you for advice!

**Comment by DannnYXZ** [comment]
Do we need to meet face to face? I thought we have discussed everything...

**Comment by aliaksandrkrasnou** [comment]
Yes, I'm kindly asking you

**Comment by aliaksandrkrasnou** [comment]
Approved, nice 👍

**Pull request closed without merging**
