### PR TITLE
Lab 4 Alexey Bobko 751001

### PR DESCRIPTION
**Pull request by Abvbobko**

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
I guess [this is not okay](https://github.com/Abvbobko/rpi-lab-4/blob/master/src/app/model.js#L6). Roughly speaking, Controller.makesApiRequests().then(updatesModel).then(updatesView). Model and view instances are better to be inside controller.
You could check out [the following example](https://alexatnet.com/model-view-controller-mvc-in-javascript/). No need to be afraid of EventEmitter, approach is the same

**Comment by Abvbobko** [comment]
Should I fix this?

**Comment by Abvbobko** [comment]
Should i fix it? There was a label "face-to-face required", but it disappeared.

**Comment by Abvbobko** [comment]
Should i fix it? There was a label "face-to-face required", but it disappeared. And can I upload lab 5 to GitHub on Monday or Tuesday?

**Comment by aliaksandrkrasnou** [comment]
Yes and yes

**Comment by aliaksandrkrasnou** [comment]
Approved, okay 👍

**Pull request closed without merging**
