### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Морозов 751001

### CODE REVIEW

**Comment by aliaksandrkrasnou** [comment]
How isPrime function could be improved? (Algorithm modification)

**Comment by aliaksandrkrasnou** [comment]
What does this mean in JS?
Apply/call/bind - explanation and difference

**Comment by aliaksandrkrasnou** [comment]
Try to finish isBracketsBalanced task

**Comment by aliaksandrkrasnou** [comment]
Prototype, inheritance in JS - prepare to explain 08-objects-tasks.js

**Comment by ghost** [comment]
> How isPrime function could be improved? (Algorithm modification)

Improved.

**Comment by ghost** [comment]
> How isPrime function could be improved? (Algorithm modification)



> Try to finish isBracketsBalanced task

Done.

**Comment by ghost** [comment]
> > Try to finish isBracketsBalanced task
> 
Done.

**Comment by ghost** [comment]
> What does this mean in JS?
> Apply/call/bind - explanation and difference

'Call' is like an ordinary function but with evidently defined 'this'.  If I realize correctly, first argument is a context and then function arguments, something like this: foo(cont, a, b, c);
Example: 
var time = {
    hours : 9,
    minutes:1,
}
set(time, 4, 4);
show(time);
function show(time)
{
    console.log(this.hours * 60 + this.minutes);
}
function set(hours, minuets)
{
     this.hours = hours;
     this.minutes = minutes;
}

'Apply' looks like 'call' but works with changeable number of arguments. As I understand it's like a va_list in C. Instead of list of arguments it uses array of them.

It seems 'bind' like a decorator in python. It makes a shell over the function it calls. 
'Bind' doesn't call a function, it returns a 'wrapper'.

If something I forgot to mention, it makes no problems to complete my answer at the lesson.

**Comment by aliaksandrkrasnou** [comment]
No need to write your answers here, we will have a conversation based on these question personally

**Comment by aliaksandrkrasnou** [comment]
Approved, okay 👍

**Pull request closed without merging**
